// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

[Index("CrsName", Name = "UQ_CourseName", IsUnique = true)]
public partial class Course
{
    [Key]
    public int CrsID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CrsName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    public int Duration { get; set; }

    [InverseProperty("Crs")]
    public virtual ICollection<Courses_Topic> Courses_Topics { get; set; } = new List<Courses_Topic>();

    [InverseProperty("Crs")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Crs")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Crs")]
    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();

    [ForeignKey("CrsID")]
    [InverseProperty("Crs")]
    public virtual ICollection<Instructor> Ins { get; set; } = new List<Instructor>();

    [ForeignKey("CrsID")]
    [InverseProperty("Crs")]
    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}