// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

[PrimaryKey("CrsID", "TopicName")]
public partial class Courses_Topic
{
    [Key]
    public int CrsID { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string TopicName { get; set; }

    [ForeignKey("CrsID")]
    [InverseProperty("Courses_Topics")]
    public virtual Course Crs { get; set; }
}