// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

public partial class Exam
{
    [Key]
    public int ExamID { get; set; }

    public int ExamDuration { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExamDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Expire_Date { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string IsActive { get; set; }

    public int CrsID { get; set; }

    [ForeignKey("CrsID")]
    [InverseProperty("Exams")]
    public virtual Course Crs { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Exam_Student_Question> Exam_Student_Questions { get; set; } = new List<Exam_Student_Question>();

    [InverseProperty("Exam")]
    public virtual ICollection<Student_Exam> Student_Exams { get; set; } = new List<Student_Exam>();

    [ForeignKey("ExamID")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question> QIDs { get; set; } = new List<Question>();
}