// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

[Table("Instructor")]
public partial class Instructor
{
    [Key]
    public int InsID { get; set; }

    public int Salary { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();

    [ForeignKey("InsID")]
    [InverseProperty("Instructor")]
    public virtual User Ins { get; set; }

    [InverseProperty("Supervisor")]
    public virtual ICollection<Track> TracksNavigation { get; set; } = new List<Track>();

    [ForeignKey("InsID")]
    [InverseProperty("Ins")]
    public virtual ICollection<Branch> BranchesNavigation { get; set; } = new List<Branch>();

    [ForeignKey("InsID")]
    [InverseProperty("Ins")]
    public virtual ICollection<Course> Crs { get; set; } = new List<Course>();

    [ForeignKey("InsID")]
    [InverseProperty("Ins")]
    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}