// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

public partial class Question
{
    [Key]
    public int QID { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string QText { get; set; }

    public int Points { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string Type { get; set; }

    public int CrsID { get; set; }

    public int CorrectOptNum { get; set; }

    [ForeignKey("CrsID")]
    [InverseProperty("Questions")]
    public virtual Course Crs { get; set; }

    [InverseProperty("QIDNavigation")]
    public virtual ICollection<Exam_Student_Question> Exam_Student_Questions { get; set; } = new List<Exam_Student_Question>();

    [InverseProperty("QIDNavigation")]
    public virtual ICollection<Questions_Option> Questions_Options { get; set; } = new List<Questions_Option>();

    [ForeignKey("QID")]
    [InverseProperty("QIDs")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}