// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int StdID { get; set; }

    public int IntakeYear { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string IsActive { get; set; }

    public int BranchID { get; set; }

    public int TrackID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("Students")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Std")]
    public virtual ICollection<Exam_Student_Question> Exam_Student_Questions { get; set; } = new List<Exam_Student_Question>();

    [ForeignKey("StdID")]
    [InverseProperty("Student")]
    public virtual User Std { get; set; }

    [InverseProperty("Std")]
    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();

    [InverseProperty("Std")]
    public virtual ICollection<Student_Exam> Student_Exams { get; set; } = new List<Student_Exam>();

    [ForeignKey("TrackID")]
    [InverseProperty("Students")]
    public virtual Track Track { get; set; }
}