// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

[PrimaryKey("StdID", "ExamID")]
public partial class Student_Exam
{
    [Key]
    public int StdID { get; set; }

    [Key]
    public int ExamID { get; set; }

    public int Score { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("Student_Exams")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("StdID")]
    [InverseProperty("Student_Exams")]
    public virtual Student Std { get; set; }
}