// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

public partial class Track
{
    [Key]
    public int TrackID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TrackName { get; set; }

    public int Duration { get; set; }

    public int Capacity { get; set; }

    public int SupervisorID { get; set; }

    [InverseProperty("Track")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    [ForeignKey("SupervisorID")]
    [InverseProperty("TracksNavigation")]
    public virtual Instructor Supervisor { get; set; }

    [ForeignKey("TrackID")]
    [InverseProperty("Tracks")]
    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();

    [ForeignKey("TrackID")]
    [InverseProperty("Tracks")]
    public virtual ICollection<Course> Crs { get; set; } = new List<Course>();

    [ForeignKey("TrackID")]
    [InverseProperty("Tracks")]
    public virtual ICollection<Instructor> Ins { get; set; } = new List<Instructor>();
}