// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

public partial class User
{
    [Key]
    public int UserID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "date")]
    public DateTime Birthdate { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Street { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Governate { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string role { get; set; }

    [InverseProperty("Ins")]
    public virtual Instructor Instructor { get; set; }

    [InverseProperty("Std")]
    public virtual Student Student { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<User_PhoneNumber> User_PhoneNumbers { get; set; } = new List<User_PhoneNumber>();
}