// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemMVC.Models;

[PrimaryKey("UserID", "PhoneNumber")]
public partial class User_PhoneNumber
{
    [Key]
    public int UserID { get; set; }

    [Key]
    public int PhoneNumber { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("User_PhoneNumbers")]
    public virtual User User { get; set; }
}